# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfcc7579ef4fe6cfdff8b56c066f5b69"
name = "xldev"
handle = "xldev"
application_url = "https://teenage-excerpt-rom-url.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-xl.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://teenage-excerpt-rom-url.trycloudflare.com/auth/callback",
  "https://teenage-excerpt-rom-url.trycloudflare.com/auth/shopify/callback",
  "https://teenage-excerpt-rom-url.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
